import type { Metadata } from "next";
import "./globals.css";
import ConditionalLayout from "./Header/components/layout/conditional-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <ConditionalLayout>{children}</ConditionalLayout>
      </body>
    </html>
  );
}
