import type { Metadata } from "next";
import "./globals.css";
import ConditionalLayout from "./Header/components/layout/conditional-layout";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
// import NavBar from "./Header/components/layout/navBar";
// import { Footer } from "./Header/components/layout/conditional-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="bg-gray-100">
        <NextIntlClientProvider messages={messages}>
          <ConditionalLayout>{children}</ConditionalLayout>

        </NextIntlClientProvider>
      </body>
    </html>
  );
}
